baseURL: /
languageCode: en-us
title: Tim Rekelj
enableEmoji: true
theme: PaperMod

params:
  env: production
  title: Tim Rekelj
  description: This is my personal blog
  defaultTheme: auto

  showReadingTime: true

  favicon: "/static/favicon.ico"

  profileMode:
        enabled: true
        title: "Tim Rekelj"
        subtitle: "My name is Tim Rekelj. I am a student at the Faculty of Computer and Information Science in Ljubljana, Slovenia. The way computers work is fascinating and this curiosity is what got me into computer science at a young age. I enjoy writing code and I wish to make it my career in the future. This is my blog, so everybody can see stuff I'm interested in and learn with me."
        imageUrl: "https://i.ibb.co/5vX0Qgj/profile.jpg"
        imageTitle: "Profile image"
        imageWidth: 120
        imageHeight: 120
        buttons:
          - name: Open blog
            url: "/posts"

  socialIcons:
    - name: github
      url: "https://github.com/timrekelj"
    - name: linkedin
      url: "https://www.linkedin.com/in/tim-rekelj-28b2a9232/"
    - name: instagram
      url: "https://www.instagram.com/timrekelj/"
    - name: spotify
      url: "https://open.spotify.com/user/9nksd7kzg4meppj2r4kg6cldg?si=fce19c5d8fb34c31"
    - name: buymeacoffee
      url: "https://www.buymeacoffee.com/timrekelj"

menu:
  main:
      - identifier: categories
        name: categories
        url: /categories/
        weight: 10
      - identifier: tags
        name: tags
        url: /tags/
        weight: 20

taxonomies:
  category: categories
  tag: tags
  series: series

outputs:
  home:
      - HTML
      - RSS
      - JSON